---
dist: focal 
language: node_js
node_js: 20.11.0 
      
env:
  global:
    - DATADOG_API_KEY={$DATADOG_API_KEY}
    - DD_API_KEY={$DD_API_KEY} 
    - DD_APP_KEY={$DD_APP_KEY}
    - DATADOG_EVENT_TITLE="Build Notification"
    - DATADOG_EVENT_TEXT="Travis CI build for Lockheed Martin"
    - DATADOG_EVENT_PRIORITY="high"
    - DATADOG_EVENT_TAGS="environment:ci,project:lmco/variable"
    - DATADOG_EVENT_ALERT_TYPE="regression"

script: 
    - npm install --save-dev @datadog/datadog-ci
    - datadog-ci -h

after_success:
  - >
    curl -X POST -H "Content-type: application/json" 
    -d "{
      \"title\": \"${DATADOG_EVENT_TITLE} - Success\",
      \"text\": \"${DATADOG_EVENT_TEXT} succeeded.\",
      \"priority\": \"${DATADOG_EVENT_PRIORITY}\",
      \"tags\": \"${DATADOG_EVENT_TAGS}\",
      \"alert_type\": \"${DATADOG_EVENT_ALERT_TYPE}\"
    }" 
    "https://api.datadoghq.com/api/v1/events?api_key=${DATADOG_API_KEY}"
curl -X POST "https://api.datadoghq.com/api/v2/ci/pipeline" \
-H "Content-Type: application/json" \
-H "DD-API-KEY: $DD_API_KEY" \
-d @- << EOF
{
  "data": {
    "attributes": {
        "resource": {
            "level": "pipeline",
            "unique_id": "845e5227-73c3-4c52-af69-9cf3a7529d09",
            "name": "lmco",
            "git": {
                "repository_url": "https://github.com/Montana/travis-datadog-notif-push/blob/master/.travis.yml",
                "author_email": "montana@linux.com",
                "sha": "cf852e17dea14008ac83036430843a1c"
            },
            "status": "success",
            "start": "2024-01-29T12:13:36-08:00",
            "end": "2024-01-29T12:13:36-08:00",
            "partial_retry": false,
            "url": "http://provider.io/pipeline/0000"
        }
    },
    "type": "cipipeline_resource_request"
  }
}
EOF                               

after_failure:
  - >
    curl -X POST -H "Content-type: application/json" 
    -d "{
      \"title\": \"${DATADOG_EVENT_TITLE} - Failure\",
      \"text\": \"${DATADOG_EVENT_TEXT} failed.\",
      \"priority\": \"${DATADOG_EVENT_PRIORITY}\",
      \"tags\": \"${DATADOG_EVENT_TAGS}\",
      \"alert_type\": \"error\"
    }" 
    "https://api.datadoghq.com/api/v1/events?api_key=${DATADOG_API_KEY}"
