language: minimal

addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk
      
env:
  global:
    - DATADOG_API_KEY={$DATADOG_API_KEY}
    - DATADOG_EVENT_TITLE="Build Notification"
    - DATADOG_EVENT_TEXT="Travis CI build for Lockheed Martin"
    - DATADOG_EVENT_PRIORITY="high"
    - DATADOG_EVENT_TAGS="environment:ci,project:lmco/variable"
    - DATADOG_EVENT_ALERT_TYPE="regression"

before_install:
   - eval "$(/opt/chefdk/bin/chef shell-init bash)"
   - chef gem install coveralls -v '0.8.19'
   - chef gem install json_spec -v '~> 1.1.4'
   - chef gem install chef-handler-datadog

install: skip

after_success:
 curl -X POST "https://api.datadoghq.com/api/v2/ci/pipeline" \
-H "Content-Type: application/json" \
-H "DD-API-KEY: $DATADOG_API_KEY" \
-d @- << EOF
{
  "data": {
    "attributes": {
        "resource": {
            "level": "pipeline",
            "unique_id": "8d3a9c03-be5d-4b8e-8b67-4a6dea7bb6a9",
            "name": "lmco",
            "git": {
                "repository_url": "https://github.com/Montana/travis-datadog-notif-push/tree/master",
                "author_email": "montana@linux.com",
                "sha": "cf852e17dea14008ac83036430843a1c"
            },
            "status": "success",
            "start": "2024-01-26T22:15:59-08:00",
            "end": "2024-01-26T22:15:59-08:00",
            "partial_retry": false,
            "url": "https://app.travis-ci.com/Montana/travis-datadog-notif-push"
        }
    },
    "type": "cipipeline_resource_request"
  }
}               

after_failure:
  - >
    curl -X POST -H "Content-type: application/json" 
    -d "{
      \"title\": \"${DATADOG_EVENT_TITLE} - Failure\",
      \"text\": \"${DATADOG_EVENT_TEXT} failed.\",
      \"priority\": \"${DATADOG_EVENT_PRIORITY}\",
      \"tags\": \"${DATADOG_EVENT_TAGS}\",
      \"alert_type\": \"error\"
    }" 
    "https://api.datadoghq.com/api/v1/events?api_key=${DATADOG_API_KEY}"
