---
language: python
python:
  - "3.7"
install:
  - pip install datadog
  
addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk
      
env:
  global:
    - DATADOG_API_KEY={$DATADOG_API_KEY}
    - DATADOG_EVENT_TITLE="Build Notification"
    - DATADOG_EVENT_TEXT="Travis CI build for Lockheed Martin"
    - DATADOG_EVENT_PRIORITY="high"
    - DATADOG_EVENT_TAGS="environment:ci,project:lmco/variable"
    - DATADOG_EVENT_ALERT_TYPE="regression"

script: 
    - datadog-ci gate evaluate 
    - pip install pytest
    - pytest test_math_functions.py 

before_install:
   - eval "$(/opt/chefdk/bin/chef shell-init bash)"
   - chef gem install coveralls -v '0.8.19'
   - chef gem install json_spec -v '~> 1.1.4'
   - chef gem install chef-handler-datadog

install: skip

after_success:
  - >
    curl -X POST -H "Content-type: application/json" 
    -d "{
      \"title\": \"${DATADOG_EVENT_TITLE} - Success\",
      \"text\": \"${DATADOG_EVENT_TEXT} succeeded.\",
      \"priority\": \"${DATADOG_EVENT_PRIORITY}\",
      \"tags\": \"${DATADOG_EVENT_TAGS}\",
      \"alert_type\": \"${DATADOG_EVENT_ALERT_TYPE}\"
    }" 
    "https://api.datadoghq.com/api/v1/events?api_key=${DATADOG_API_KEY}"

after_failure:
  - >
    curl -X POST -H "Content-type: application/json" 
    -d "{
      \"title\": \"${DATADOG_EVENT_TITLE} - Failure\",
      \"text\": \"${DATADOG_EVENT_TEXT} failed.\",
      \"priority\": \"${DATADOG_EVENT_PRIORITY}\",
      \"tags\": \"${DATADOG_EVENT_TAGS}\",
      \"alert_type\": \"error\"
    }" 
    "https://api.datadoghq.com/api/v1/events?api_key=${DATADOG_API_KEY}"
